"""rename address

Revision ID: aed0d4311e04
Revises: f5e29e902340
Create Date: 2025-01-18 12:15:27.317357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed0d4311e04'
down_revision = 'f5e29e902340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name="location")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name="address")
    # ### end Alembic commands ###
