"""rename department

Revision ID: f5e29e902340
Revises: d4fa47ec8f54
Create Date: 2025-01-18 12:09:14.572303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5e29e902340'
down_revision = 'd4fa47ec8f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
